### ISSUE TITLE
Which evnironment used?

### ISSUE THREAD

**Issue by geniys** [bistros/candidate-crawler#1]
Can you describe used evnironment?

And I try to change it for Ubuntu

Below works are tested on Ubuntu 14.04.2 x64

### 1. Install Java8

```vim
$sudo apt-add-repository ppa:webupd8team/java
$sudo apt-get update
$sudo apt-get install oracle-java8-installer
```

### 2. Other prerequisites (git, mvn)
```vim
$sudo apt-get update
$sudo apt-get install git maven
```

### Build
TB

**Comment by bistros** [comment]
@geniys  
mvn install
java -jar -Dspring.profiles.active=production ./target/candidate-crawler-1.0-SNAPSHOT.jar &

**Comment by geniys** [comment]
Thanks. It works
